sudo: required
language: cpp

compiler:
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - libboost-dev
      - libgtest-dev
      - libreadline6
      - libreadline6-dev
      - cmake
      - cmake-data

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make all test
